[package]
name = "rw_memory_ex"
description = "rw_memory_ex example [trickster]"
version = "0.0.1"
license = "MIT"
authors = ["Igor Klepacki <nullopt@riseup.net>"]

[dependencies]
trickster = { path = "../.." }