[package]
name = "get_pid"
description = "get_pid example [trickster]"
version = "0.0.1"
license = "MIT"
authors = ["Igor Klepacki <nullopt@riseup.net>"]

[dependencies]
trickster = { path = "../.." }